### ISSUE TITLE
episode_by_number return is empty

### ISSUE THREAD

**Issue by Wire64** [bmartins/WWW-TVMaze#1]
Hi Bruno Martins,

I think i found an issue in episode_by_number.

episode_by_number unexpectedly returns empty on some episodes while it should contain the episode details.

`$tv_maze->episode_by_number(3333, 1, 1)`
returns correct details

`$tv_maze->episode_by_number(3333, 7, 11)`
returns correct details

But on:
`$tv_maze->episode_by_number(3333, 7, 12)`
return is **empty**

`$tv_maze->episode_by_number(3333, 8, 1)`
return is **empty**

`$tv_maze->episode_by_number(3333, 8, 2)`
return is **empty**

The episodes exists in _show_episode_list_ and on http://api.tvmaze.com/shows/3333/episodebynumber?season=7&number=12

Thanks,
Wire64

**Comment by bmartins** [comment]
sorry for the delay, somehow I missed the notification about the issue. will take care of that

Thanks

**Comment by bmartins** [comment]
fixed
